LoadPackage("kbmag");;
all_ok := true;;
rws := ReadRWS("direct_rws/n0_y1_p1_p1.rws");;
ResetRWS(rws);;
attempt := CALL_WITH_CATCH(KnuthBendix,[rws]);;
freegens := GeneratorsOfGroup(FreeStructureOfRewritingSystem(rws));;
reductions := List(freegens,z->ReducedForm(rws,z));;
ok := attempt=[true,true] and IsConfluent(rws) and ForAll(reductions,IsOne);;
Print("replay n0_y1_p1_p1: KB=",attempt,", confluent=",IsConfluent(rws)," generator_normal_forms=",reductions," ok=",ok,"\n");
if not ok then all_ok := false; fi;
rws := ReadRWS("direct_rws/n0_y1_p1_m1.rws");;
ResetRWS(rws);;
attempt := CALL_WITH_CATCH(KnuthBendix,[rws]);;
freegens := GeneratorsOfGroup(FreeStructureOfRewritingSystem(rws));;
reductions := List(freegens,z->ReducedForm(rws,z));;
ok := attempt=[true,true] and IsConfluent(rws) and ForAll(reductions,IsOne);;
Print("replay n0_y1_p1_m1: KB=",attempt,", confluent=",IsConfluent(rws)," generator_normal_forms=",reductions," ok=",ok,"\n");
if not ok then all_ok := false; fi;
rws := ReadRWS("direct_rws/n0_y1_m1_p1.rws");;
ResetRWS(rws);;
attempt := CALL_WITH_CATCH(KnuthBendix,[rws]);;
freegens := GeneratorsOfGroup(FreeStructureOfRewritingSystem(rws));;
reductions := List(freegens,z->ReducedForm(rws,z));;
ok := attempt=[true,true] and IsConfluent(rws) and ForAll(reductions,IsOne);;
Print("replay n0_y1_m1_p1: KB=",attempt,", confluent=",IsConfluent(rws)," generator_normal_forms=",reductions," ok=",ok,"\n");
if not ok then all_ok := false; fi;
rws := ReadRWS("direct_rws/n0_y1_m1_m1.rws");;
ResetRWS(rws);;
attempt := CALL_WITH_CATCH(KnuthBendix,[rws]);;
freegens := GeneratorsOfGroup(FreeStructureOfRewritingSystem(rws));;
reductions := List(freegens,z->ReducedForm(rws,z));;
ok := attempt=[true,true] and IsConfluent(rws) and ForAll(reductions,IsOne);;
Print("replay n0_y1_m1_m1: KB=",attempt,", confluent=",IsConfluent(rws)," generator_normal_forms=",reductions," ok=",ok,"\n");
if not ok then all_ok := false; fi;
rws := ReadRWS("direct_rws/n1_y2_p1_p1.rws");;
ResetRWS(rws);;
attempt := CALL_WITH_CATCH(KnuthBendix,[rws]);;
freegens := GeneratorsOfGroup(FreeStructureOfRewritingSystem(rws));;
reductions := List(freegens,z->ReducedForm(rws,z));;
ok := attempt=[true,true] and IsConfluent(rws) and ForAll(reductions,IsOne);;
Print("replay n1_y2_p1_p1: KB=",attempt,", confluent=",IsConfluent(rws)," generator_normal_forms=",reductions," ok=",ok,"\n");
if not ok then all_ok := false; fi;
rws := ReadRWS("direct_rws/n1_y2_p1_m1.rws");;
ResetRWS(rws);;
attempt := CALL_WITH_CATCH(KnuthBendix,[rws]);;
freegens := GeneratorsOfGroup(FreeStructureOfRewritingSystem(rws));;
reductions := List(freegens,z->ReducedForm(rws,z));;
ok := attempt=[true,true] and IsConfluent(rws) and ForAll(reductions,IsOne);;
Print("replay n1_y2_p1_m1: KB=",attempt,", confluent=",IsConfluent(rws)," generator_normal_forms=",reductions," ok=",ok,"\n");
if not ok then all_ok := false; fi;
rws := ReadRWS("direct_rws/n1_y2_m1_p1.rws");;
ResetRWS(rws);;
attempt := CALL_WITH_CATCH(KnuthBendix,[rws]);;
freegens := GeneratorsOfGroup(FreeStructureOfRewritingSystem(rws));;
reductions := List(freegens,z->ReducedForm(rws,z));;
ok := attempt=[true,true] and IsConfluent(rws) and ForAll(reductions,IsOne);;
Print("replay n1_y2_m1_p1: KB=",attempt,", confluent=",IsConfluent(rws)," generator_normal_forms=",reductions," ok=",ok,"\n");
if not ok then all_ok := false; fi;
rws := ReadRWS("direct_rws/n1_y2_m1_m1.rws");;
ResetRWS(rws);;
attempt := CALL_WITH_CATCH(KnuthBendix,[rws]);;
freegens := GeneratorsOfGroup(FreeStructureOfRewritingSystem(rws));;
reductions := List(freegens,z->ReducedForm(rws,z));;
ok := attempt=[true,true] and IsConfluent(rws) and ForAll(reductions,IsOne);;
Print("replay n1_y2_m1_m1: KB=",attempt,", confluent=",IsConfluent(rws)," generator_normal_forms=",reductions," ok=",ok,"\n");
if not ok then all_ok := false; fi;
if not all_ok then Error("exported rewriting-system replay failed"); fi;
Print("ALL EIGHT EXPORTED SYSTEMS REPLAYED\n");
QUIT;;
