#!/usr/bin/env python3
"""Export the sealed complement presentation Q and the eight named loops to GAP.

Reads only ../sealed_transport/r_presentations.json (digest recorded in the
output) and writes generation_input.g: the three-generator, 78-relator
presentation Q of pi_1(C_aud) and the tracked words geom_x, geom_y, geom_r,
geom_s, geom_A, geom_B, geom_M, geom_N as words in its generators.
"""
import hashlib, json
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE.parent / "sealed_transport" / "r_presentations.json"
NAMES = ["x", "y", "r", "s", "A", "B", "M", "N"]


def gword(word):
    if not word:
        return "One(F)"
    return "*".join(f"g{abs(a)}^{-1 if a < 0 else 1}" for a in word)


def main():
    raw = SRC.read_bytes()
    data = json.loads(raw)
    assert data["format"] == "luttinger-filled-presentations-v1"
    assert data["ngens"] == 3 and len(data["relators"]) == 78
    tracked = data["tracked_words"]
    lines = [
        "# generated by export_generation_input.py; do not edit",
        f"# source: sealed_transport/r_presentations.json sha256 {hashlib.sha256(raw).hexdigest()}",
        'F := FreeGroup("g1","g2","g3");; g1 := F.1;; g2 := F.2;; g3 := F.3;;',
        "rels := [",
        ",\n".join("  " + gword(r) for r in data["relators"]),
        "];;",
    ]
    for n in NAMES:
        lines.append(f"w_{n} := {gword(tracked['geom_' + n])};;")
    (HERE / "generation_input.g").write_text("\n".join(lines) + "\n")
    print(f"wrote generation_input.g: 78 relators, {len(NAMES)} named loops, "
          f"source sha256 {hashlib.sha256(raw).hexdigest()[:12]}")


if __name__ == "__main__":
    main()
